name: CI

# 在master分支发生push事件时触发。
on:
  push:
    branches:
      - master

jobs: # 工作流
  build: # 自定义名称
    runs-on: ubuntu-latest #运行在虚拟机环境ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps: # 步骤
      - name: Checkout 🛎️
        uses: actions/checkout@v1 # 使用的动作。格式：userName/repoName。作用：检出仓库，获取源码。 官方actions库：https://github.com/actions

      - name: Use Node.js ${{ matrix.node-version }} # 步骤2
        uses: actions/setup-node@v1 # 作用：安装nodejs
        with:
          node-version: ${{ matrix.node-version }} # 版本

      # - name: run deploy.sh # 步骤3 （同时部署到github和coding）
      #   env: # 设置环境变量
      #     GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }} # toKen私密变量
      #     # CODING_TOKEN: ${{ secrets.CODING_TOKEN }}
      #   run: npm install && npm run deploy

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install
          npm run build
          cd docs/.vuepress/dist
          cd -
      - name: Deploy to gh-page 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5 # 作用：将项目构建和部署到github。 https://github.com/JamesIves/github-pages-deploy-action
        with:
          branch: gh-page # The branch the action should deploy to.
          target-folder: blog #部署到gh-page的blog目录下
          folder: docs/.vuepress/dist # The folder the action should deploy.

      - name: run baiduPush.sh # 运行百度推送
        run: npm run baiduPush

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@main # 使用别人包装好的步骤镜像
        env: 
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }} # 引用配置，SSH私钥
          ARGS: "-rltgoDzvO --delete" # rsync参数，
          SOURCE: docs/.vuepress/dist/ # 要推送的文件夹，路径相对于代码仓库的根目录
          REMOTE_HOST: ${{ secrets.SSH_HOST }} # 引用配置，服务器的host名（IP或者域名domain.com）
          REMOTE_USER: ${{ secrets.SSH_USERNAME }} # 引用配置，服务器登录名
          TARGET: ${{ secrets.SERVER_DESTINATION }} # 部署到目标文件夹


      # - name: Sync to Gitee
      #   uses: wearerequired/git-mirror-action@master
      #   env:
      #     # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
      #     SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
      #   with:
      #     # 注意替换为你的 GitHub 源仓库地址
      #     source-repo: git@github.com:SaulJWu/SaulJWu.github.io.git
      #     # 注意替换为你的 Gitee 目标仓库地址
      #     destination-repo: git@gitee.com:SaulJWu/SaulJWu.git

      # - name: Build Gitee Pages
      #   uses: yanglbme/gitee-pages-action@master
      #   with:
      #     # 注意替换为你的 Gitee 用户名
      #     gitee-username: SaulJWu
      #     # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
      #     gitee-password: ${{ secrets.GITEE_PASSWORD }}
      #     # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
      #     gitee-repo: SaulJWu/SaulJWu
      #     # 要部署的分支
      #     branch: gh-pages